swagger: '2.0'
info:
  version: 1.0.0
  title: 'Very Simple IAAS'
paths:
  /v1/nodes:
    post:
      description: Create a node
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: nodeRequest 
          in: body
          description: a node request
          required: true
          schema:
            $ref: '#/definitions/NodeRequest'
      responses:
        202:
          description: A request ID.
        400:
          description: |
            When the request is malformated or when mandatory arguments are missing
        500:
          description: Unhandled error.
        502:
          description: Execution backend not available
definitions:
  NodeRequest:
    description: A Node Request object
    properties:
      kind:
        type: string
        description: The OS type
      size:
        type: string
        description: The size of the (virtual) machine
      disksize:
        type: integer
        format: int32
        description: The initial disk capacity size (in GB)
      leasedays:
        type: integer
        format: int32
        description: The lease
      environment_type:
        type: string
        description: the target environment
      description:
        type: string
